# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GaussianKernelDensity <- function(X) {
    .Call('_kre_GaussianKernelDensity', PACKAGE = 'kre', X)
}

UniformKernelDensity <- function(X) {
    .Call('_kre_UniformKernelDensity', PACKAGE = 'kre', X)
}

QuarticKernelDensity <- function(X) {
    .Call('_kre_QuarticKernelDensity', PACKAGE = 'kre', X)
}

TriweightKernelDensity <- function(X) {
    .Call('_kre_TriweightKernelDensity', PACKAGE = 'kre', X)
}

EpanechnikovKernelDensity <- function(X) {
    .Call('_kre_EpanechnikovKernelDensity', PACKAGE = 'kre', X)
}

